### ISSUE TITLE
Lỗi không public được

### ISSUE THREAD

**Issue by chienag09** [lbngoc/fb-masspost#1]
[Error] Cannot publish post to (NHÓM) Cộng đồng người Việt sống và làm việc tại Nhật.: An error occurred while processing this request. Please try again later.
[Info] Your next session will be available at 2016-11-10 10:55:50 +0700. If you find any bugs, please help to report them.
[Warning] Your session will be expired at 2016-11-10 11:00:00 +0700.
![loib](https://cloud.githubusercontent.com/assets/21999690/20162508/1fe3bf12-a728-11e6-9ba4-c30093325fd7.png)

**Comment by lbngoc** [comment]
@chienag09 thanks bạn đã report nhé, bạn gửi mình cái link vào group này để mình check lại với ^^
p.s hiện tại theo mình test thì vài group để chế độ kiểm duyệt bài đăng thì tool mình ko post lên được, bạn check xem các group khác có bị lỗi này không để mình xem do setting của group hay do tool mình có bug nha.
